### PR TITLE
Improve preview sound quality

### PR DESCRIPTION
**Pull request by ZoomTen**
This should make the preview better represent the Game Boy sound

### CODE REVIEW

**Comment by ZoomTen** [comment]
Increased sample size instead of changing the interpolation mode.

**Comment by dannye** [comment]
Hmm, at first listen, this is an improvement for a lot of channel 3's low notes, but it has some side effects with high notes.
For example, listen to channel 2 in [pokemontower.asm](https://github.com/dannye/pokered-crysaudio/blob/master/crysaudio/music/RBY/pokemontower.asm), especially the second half of the song.

**Comment by ZoomTen** [comment]
Interesting balance to try and strike indeed...
I'll try some more combos and see how it works out

**Comment by dannye** [comment]
Gonna close this for being outdated, but please feel free to open another PR if you take another attempt at this.

**Pull request closed without merging**
